branch-defaults:
  server:
    environment: CoffRefugee-dev
global:
  application_name: CoffRefugee
  default_ec2_keyname: karmakoffee
  default_platform: Python 3.4
  default_region: us-west-2
  profile: eb-cli
  sc: git
